apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure-portfolio
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 64.0.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        alertmanager:
          ingress:
            enabled: true
            hosts:
              - alertmanager.local.gd
            tls:
              - secretName: local-tls
                hosts:
                  - alertmanager.local.gd
        grafana:
          adminPassword: "asdasd"
          ingress:
            enabled: true
            hosts:
              - grafana.local.gd
            tls:
              - secretName: local-tls
                hosts:
                  - grafana.local.gd
        prometheus:
          ingress:
            enabled: true
            hosts:
              - prometheus.local.gd
            tls:
              - secretName: local-tls
                hosts:
                  - prometheus.local.gd
          prometheusSpec:
            additionalScrapeConfigs: []
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            retention: 7d
            namespaceSelector:
              any: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
